config/routes.rb
Rails.application.routes.draw do
  resources :tags
  authenticate :user do
    resources :reactions
    post 'reactions/bulk', to: 'reactions#bulk_new', as: 'reactions_bulk_new'
    post 'reactions/bulk/create', to: 'reactions#bulk_create', as: 'reactions_bulk_create'
    resources :tags
    resources :vulnerabilities, only: [:index, :show, :update, :edit]
    resources :projects
    get 'nvd_update', to: 'vulnerabilities#nvd', as: 'nvd_update'
    get 'nvd_load_year/:year', to: 'vulnerabilities#nvd_load_year', as: 'nvd_load_year'
    get 'relevant_vulnerabilities', to: 'vulnerabilities#relevant', as: 'relevant_vulnerabilities'
  end
  
#  DisableRegistration = Rails.env.production? && false
#  if DisableRegistration
#    devise_for :users, :controllers => { :registrations => "registrations" } 
#  else
    devise_for :users
#  end

  root to: 'static#home'

  get 'noscript', to: 'static#noscript'
  get 'about', to: 'static#about'
  get 'terms', to: 'static#terms'
  get 'impressum', to: 'static#impressum', as: 'impressum'
  get 'datenschutz', to: 'static#datenschutz', as: 'datenschutz'
  get 'contact', to: 'static#contact', as: 'contact'
  
end

app/views/shared/_affected_system.html.erb
<div class="component-in-table">
<%=render vulnerability.tags%>
</div>

app/views/shared/_back_links.html.haml
= link_to "Relevant Vulnerabilities", relevant_vulnerabilities_path
= link_to "All Vulnerabilities", vulnerabilities_path

app/views/shared/_component.html.erb
<div class="component-in-table">
<%=render vulnerability.tags%>
</div>

app/views/shared/_last_update_nvd.html.erb
<% deadline = 8 #hours %>
<% if NvdUpdate.last <= deadline.hours.ago %>
  <div class="alert alert-warning" role="alert">
   The vulnerabilities are older than <%=deadline%> hours!
<%= link_to "Update", nvd_update_path, class: 'btn btn-primary', id: 'update', target: '_blank' %> </div>
<% end %>