config/routes.rb
Rails.application.routes.draw do
  resources :tags
  authenticate :user do
    resources :reactions
    post 'reactions/bulk', to: 'reactions#bulk_new', as: 'reactions_bulk_new'
    post 'reactions/bulk/create', to: 'reactions#bulk_create', as: 'reactions_bulk_create'
    resources :tags
    resources :vulnerabilities, only: [:index, :show, :update, :edit]
    resources :projects
    get 'nvd_update', to: 'vulnerabilities#nvd', as: 'nvd_update'
    get 'nvd_load_year/:year', to: 'vulnerabilities#nvd_load_year', as: 'nvd_load_year'
    get 'relevant_vulnerabilities', to: 'vulnerabilities#relevant', as: 'relevant_vulnerabilities'
  end
  
#  DisableRegistration = Rails.env.production? && false
#  if DisableRegistration
#    devise_for :users, :controllers => { :registrations => "registrations" } 
#  else
    devise_for :users
#  end

  root to: 'static#home'

  get 'noscript', to: 'static#noscript'
  get 'about', to: 'static#about'
  get 'terms', to: 'static#terms'
  get 'impressum', to: 'static#impressum', as: 'impressum'
  get 'datenschutz', to: 'static#datenschutz', as: 'datenschutz'
  get 'contact', to: 'static#contact', as: 'contact'
  
end

app/models/project.rb
require 'set'
require 'couch'

class Project < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true

  after_save {|project| Couch.update_view_for_project project}

  def systems()
    prepare_description
  end
  
  private
  
  #shall return a list of strings with subsystems out of description
  def prepare_description()
    #  remove comments  and consequitive empty lines   and  leading and trailing spaces the split
    res = Set.new
    if systems_description.nil? || systems_description.blank?
      return res
    end

    lines = systems_description.gsub(/#.*$/, '').gsub(/\n+|\r+/,"\n").squeeze("\n").gsub(/^\s+/,'').gsub(/\s+$/,'').split("\n")
    lines.each do |line|
      line.split(',').each do |sys|
        # remove repeating spaces and leading and trailing spaces
        sys = sys.gsub(/\s+/,' ').gsub(/^\s+/,'').gsub(/\s+$/,'')
        res.add(sys)
      end
    end
    return res.to_a
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource  
  before_action :alert_on_huge_projects
  before_action :set_viewing_projects

  def set_viewing_projects
    @viewing_projects = true
  end

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, flash: { success: 'Project was successfully created.' }}
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, flash: { success: 'Project was successfully updated.' }}
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, flash: { success: 'Project was successfully destroyed.' }}
      format.json { head :no_content }
    end
  end

  private
    def project_params
      params.require(:project).permit(:name, :systems_description, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description, 'Describe it in few words, please:' %>
    <%= form.text_field :description, id: :project_description, class: "form-control"%>
  </div>


  <div class="form-group">
    <%= form.label :systems_description, "Components:" %>

<p>
Components are the list of keywords which will be searched in 
the vulnerabilities to match your project.
<br><em>Example:</em>
<pre><code># Operating system and its components
OpenBSD
perl, python, ruby
gcc, clang

# Libraries actively used
libxml, libiberty</code></pre></p>

    <%= form.text_area :systems_description, id: :project_systems_description, 
        class: "form-control", rows: "10", 
        placeholder: "Copy and paste from the example above for starters." %>
      
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %> 
  </div>
<% end %>

app/views/projects/edit.html.erb
<h3>Editing Project</h3>

<%= render 'form', project: @project %>
<br>
<%= link_to 'Cancel', @project, class: 'cancel-link' %> 

<div class='back-links'>
<%= link_to 'Projects', projects_path %>
<%= render 'shared/back_links' %>
</div>

app/views/projects/index.html.erb
<div class="container">
<p>Your Projects</p>

<% if current_user.projects.count > 0 %>

<table class="table table-responsive table-striped">
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td class="project_name"><%= link_to project.name, project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Delete project', project, method: :delete, 
                 data: { confirm: 'Do you really want to delete ' + project.name + '?  - This can not be undone.' } 
              %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to ' + New Project', new_project_path %>
<br>
<br>
<br>
<br>
<br>
<%= link_to "View Relevant Vulnerabilities", relevant_vulnerabilities_path, class: "btn btn-primary" %>

<% else %>
<p>You do not have any projects yet.</p>
<p>Please, create a project to track vulnerabilities within its components.</p>

<%= link_to 'Create First Project', new_project_path, class: 'btn btn-primary' %>
<% end %>


</div>

app/views/projects/new.html.erb
<h3>New Project</h3>

<%= render 'form', project: @project %>

<div class='back-links'>
<%= link_to 'Projects', projects_path %>
<%= render 'shared/back_links' %>
</div>

app/views/projects/show.html.erb
<a id="top"></a>
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>


<p>
<strong>Actions</strong>

<div class="actions">
  <%= link_to 'Edit', edit_project_path(@project), class: 'btn' %>
  <%= link_to "View Relevant Vulnerabilities", relevant_vulnerabilities_path(project: @project.id), class: "btn btn-primary" %>
</div>

<div class='back-links'>
<%= link_to 'Projects', projects_path %>
<%= render 'shared/back_links' %>
</div>


</p>

<p>
  <strong>This is how vulnswatch see your components now:</strong>
  <div class="systems_sorted"><%= @project.systems.sort.join(', ') %></div>
</p>

<p>
  <strong>Components as you have described them:</strong>
  <pre><code class="project-systems-description"><%=@project.systems_description%></code></pre>
</p>

<br>
<%= link_to 'Edit', edit_project_path(@project), class: 'btn' %> |
<a href="#top" class='btn'>Go to top</a>

<br>

<div class='back-links'>
<%= link_to 'Projects', projects_path %>
<%= render 'shared/back_links' %>
</div>