config/routes.rb
Rails.application.routes.draw do
  resources :tags
  authenticate :user do
    resources :reactions
    post 'reactions/bulk', to: 'reactions#bulk_new', as: 'reactions_bulk_new'
    post 'reactions/bulk/create', to: 'reactions#bulk_create', as: 'reactions_bulk_create'
    resources :tags
    resources :vulnerabilities, only: [:index, :show, :update, :edit]
    resources :projects
    get 'nvd_update', to: 'vulnerabilities#nvd', as: 'nvd_update'
    get 'nvd_load_year/:year', to: 'vulnerabilities#nvd_load_year', as: 'nvd_load_year'
    get 'relevant_vulnerabilities', to: 'vulnerabilities#relevant', as: 'relevant_vulnerabilities'
  end
  
#  DisableRegistration = Rails.env.production? && false
#  if DisableRegistration
#    devise_for :users, :controllers => { :registrations => "registrations" } 
#  else
    devise_for :users
#  end

  root to: 'static#home'

  get 'noscript', to: 'static#noscript'
  get 'about', to: 'static#about'
  get 'terms', to: 'static#terms'
  get 'impressum', to: 'static#impressum', as: 'impressum'
  get 'datenschutz', to: 'static#datenschutz', as: 'datenschutz'
  get 'contact', to: 'static#contact', as: 'contact'
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :vulnerability
  belongs_to :user
  validates :user_id, presence: true
  validates :vulnerability_id, presence: true
  validates_uniqueness_of :component, scope: :vulnerability_id
  validates :component, presence: true, allow_blank: false

  after_save{|tag| Couch.put_vulnerability tag.vulnerability}

  def component=(val)
    write_attribute(:component, val.gsub(/^\s+/, '').gsub(/\s+$/, ''))
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource  

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, flash: { success: 'Tag was successfully created.' }}
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, flash: { success: 'Tag was successfully updated.' }}
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    vuln = @tag.vulnerability
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to vuln, flash: { success: 'Tag was successfully destroyed.' }}
      format.json { head :no_content }
    end
  end

  private
    def tag_params
      res = params.require(:tag).permit(:component, :vulnerability)
      vuln = Vulnerability.find_by(name: params["tag"]["vulnerability"])
      res.delete("vulnerability")
      res["vulnerability_id"] = vuln.nil? ? "" : vuln.id
      res
    end
end

app/helpers/tags_helper.rb
module TagsHelper
  def link_to_tag(vulnerability, other={})
    link_to ' + Add Tag', new_tag_path('tag[vulnerability]' => vulnerability.name), other
  end

  def link_to_delete_tag(tag, title='Delete', other={})
    other[:method] = :delete
    other[:data] = { confirm: "Un-tag #{tag.vulnerability.name} with #{tag.component}?" }
    link_to title, tag, other
  end
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :component %>
    <%= form.text_field :component, id: :tag_component, class: "form-control", placeholder: 'e.g. perl'  %>
  </div>

  <div class="form-group">
    <%= form.label :vulnerability %>
    <%= form.text_field :vulnerability, id: :tag_vulnerability, class: "form-control", value: name_or_nil(form.object.vulnerability), placeholder: 'CVE-2017-1234' %>
  </div>

  <div class="vulnerability-summary"><%= form.object.vulnerability.name %>:&nbsp; <%= form.object.vulnerability.summary %></div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.haml
%div.vulnerability-tag
  =link_to tag.component, tag, class: 'tag-link'
  -if tag.user == current_user
    =link_to_delete_tag tag, 'x', class: 'delete-tag-x'

app/views/tags/edit.html.erb
<h3>Editing Tag</h3>

<%= render 'form', tag: @tag %>

<br>
<%= link_to 'Cancel', @tag, class: 'cancel-link' %>

<div class='back-links'>
<%= render 'shared/back_links' %>
</div>

app/views/tags/index.html.erb
<h3>Your Tags</h3>

<div class='container'>

<% if @tags.any? %>

<table class="index_table table-striped">
  <thead>
    <tr>
      <th colspan='2'>Vulnerability</th>
      <th>Component</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= link_to tag.vulnerability.name, edit_tag_path(tag) %></td>
        <td><%= shorten(tag.vulnerability.summary) %></td>
        <td><%= tag.component %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to_delete_tag(tag) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
<p>
  No tags yet.
</p>

<p>With tags you can mark vulnerabilities with components they affect.</p>

<% end %>


<br>

<%= link_to ' + New Tag', new_tag_path %>

</div>

app/views/tags/new.html.erb
<h3>New Tag</h3>

<%= render 'form', tag: @tag %>

<div class='back-links'>
<%= render 'shared/back_links' %>
</div>

app/views/tags/show.html.erb
<h3>Tag</h3>
<p>
  <strong>Component affected by vulnerability:</strong>
  <%= @tag.component %>
</p>

<p>
  <strong>Vulnerability:</strong>
  <%= link_to_vulnerability @tag.vulnerability %>
</p>

<div class="vulnerability-summary"><%= @tag.vulnerability.summary %></div>



<p>
  <strong>By:</strong>
  <%= @tag.user.name %>
</p>

<% if can? :edit, @tag %>
<%= link_to 'Edit', edit_tag_path(@tag), id: 'edit-button' %>
<% end %>

<% if can? :destroy, @tag %>
<%= link_to 'Delete', @tag, method: :delete, data: { confirm: 'Are your sure you want to delete this tag?' }, id: 'delete-button' %>
<% end %>

<div class='back-links'>
<%= render 'shared/back_links' %>
</div>