config/routes.rb
Rails.application.routes.draw do
  resources :tags
  authenticate :user do
    resources :reactions
    post 'reactions/bulk', to: 'reactions#bulk_new', as: 'reactions_bulk_new'
    post 'reactions/bulk/create', to: 'reactions#bulk_create', as: 'reactions_bulk_create'
    resources :tags
    resources :vulnerabilities, only: [:index, :show, :update, :edit]
    resources :projects
    get 'nvd_update', to: 'vulnerabilities#nvd', as: 'nvd_update'
    get 'nvd_load_year/:year', to: 'vulnerabilities#nvd_load_year', as: 'nvd_load_year'
    get 'relevant_vulnerabilities', to: 'vulnerabilities#relevant', as: 'relevant_vulnerabilities'
  end
  
#  DisableRegistration = Rails.env.production? && false
#  if DisableRegistration
#    devise_for :users, :controllers => { :registrations => "registrations" } 
#  else
    devise_for :users
#  end

  root to: 'static#home'

  get 'noscript', to: 'static#noscript'
  get 'about', to: 'static#about'
  get 'terms', to: 'static#terms'
  get 'impressum', to: 'static#impressum', as: 'impressum'
  get 'datenschutz', to: 'static#datenschutz', as: 'datenschutz'
  get 'contact', to: 'static#contact', as: 'contact'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>vulnswatch - vulnerability management software</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <% if ! ( controller_name == "static" and action_name == "noscript" ) %>
       <noscript>
          <META HTTP-EQUIV="Refresh" CONTENT="0;URL=<%= noscript_path %>">
       </noscript>
    <% else # on the noscript page %>
       <script>
         window.location.replace("<%= root_url %>")
       </script>
    <% end %>
    
    <%= favicon_link_tag 'vulnswatch.64.png' %>

  </head>

  <body>

     <% if ! ( controller_name == "static" and action_name == "noscript" ) %>
       <noscript>
        <p>You are redirected to an error page, because JavaScript is disabled in your browser...</p>
       </noscript>
    <% end %>
 
    <nav class="navbar navbar-light navbar-expand-lg">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag 'vulnswatch.32.png' %>
        <%= 'vulnswatch' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="navbar-collapse collapse" id="navbarNav">
        <ul class='navbar-nav mr-auto'>
          <% if user_signed_in? %>
              <li class='nav-item'><%= link_to 'Relevant Vulnerabilities', relevant_vulnerabilities_path, class: (!@searching_relevants.nil? && @searching_relevants) ? 'nav-link active' : 'nav-link' %></li>
              <li class='nav-item'><%= link_to 'All Vulnerabilities', vulnerabilities_path(project: ""),  class: (!@searching_relevants.nil? && !@searching_relevants)  ? 'nav-link active' : 'nav-link' %></li>
              <li class='nav-item'><%= link_to 'Projects', projects_path, class: @viewing_projects? 'nav-link active' : 'nav-link' %></li>
              <li class='nav-item'><%= link_to 'Reactions', reactions_path, class: @viewing_reactions? 'nav-link active' : 'nav-link' %></li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-item' %>
                  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </div>
              </li>
            <% else %>
              <li class='nav-item'><%= link_to 'Log In', new_user_session_path, class: 'nav-link' %></li>
              <li class='nav-item'><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %></li>
            <% end %>
        </ul>
      </div> <!-- nav bar --!>
    </nav>

    <div class="container"> 
     <!-- flash messages -->
     <% flash.each do |key, value| %>
        <% if key =="notice" %>
        <%   key="info"  %>
        <% end %>
       <div class="alert alert-<%= key %>" role="alert">
         <%= value %>
       </div>
     <% end %>
    </div>
    
    <div class="container-fluid ml-1 mr-1">
    <!-- top content -->
    <%= yield :top_content %>

    <!-- main yield -->
    
      <h1><%= yield :header %></h1>
      <%= yield %>
    </div>
  

    <nav class="navbar navbar-light navbar-expand-lg">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavBottom" 
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="navbar-collapse collapse" id="navbarNavBottom">
        <ul class='navbar-nav mr-auto'>
          <li><%= link_to 'Impressum', impressum_path, class: 'nav-link' %></li>
          <li><%= link_to 'Contact', contact_path, class: 'nav-link' %></li>
          <li><%= link_to 'Datenschutz', datenschutz_path, class: 'nav-link' %></li>
          <li><%= link_to 'Terms of Use', terms_path, class: 'nav-link' %></li>
          <li><%= link_to_issues %></li>
          <li><%= link_to 'About', about_path, class: 'nav-link' %></li>
        </ul>
      </div>
    </nav>

  </body>

</html>